In [19]:
import numpy as np
import cv2 as cv
import glob
import os

In [20]:
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)

xdim=5
ydim = 4
objp = np.zeros((xdim*ydim,3), np.float32)
objp[:,:2] = np.mgrid[0:xdim,0:ydim].T.reshape(-1,2)
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = []
images = [os.path.join(".",a+".png") for a in ["calib3","calib4","calib6"]]
print(images)

['.\\calibration\\calib1.png', '.\\calibration\\calib2.png', '.\\calibration\\calib3.png', '.\\calibration\\calib4.png', '.\\calibration\\calib5.png', '.\\calibration\\calib6.png', '.\\calibration\\calib7.png']


In [21]:
for fname in images:
    print("reading "+fname)
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (xdim,ydim), None)
    # If found, add object points, image points (after refining them)
    print("we got "+str(ret)+" "+str(corners))
    if ret == True:
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)
        # Draw and display the corners
        cv.drawChessboardCorners(img, (xdim,ydim), corners2, ret)
        cv.imshow('img', img)
        cv.waitKey(0)
cv.destroyAllWindows()

reading .\calibration\calib1.png
we got False None
reading .\calibration\calib2.png
we got False None
reading .\calibration\calib3.png
we got True [[[ 409.16833  769.2327 ]]

 [[ 467.38077  577.99634]]

 [[ 514.3766   420.72256]]

 [[ 553.3396   288.76617]]

 [[ 585.88275  175.54607]]

 [[ 660.47504  769.1612 ]]

 [[ 693.8731   579.1462 ]]

 [[ 720.9976   423.372  ]]

 [[ 743.03613  291.3232 ]]

 [[ 761.75745  177.56097]]

 [[ 906.7988   769.75336]]

 [[ 916.4699   580.2616 ]]

 [[ 923.5824   424.45386]]

 [[ 929.98706  292.9664 ]]

 [[ 936.64703  179.22238]]

 [[1154.5377   771.9184 ]]

 [[1139.1713   581.418  ]]

 [[1127.7035   425.17636]]

 [[1118.2294   292.62527]]

 [[1111.8695   178.60521]]]
reading .\calibration\calib4.png
we got True [[[1097.3898    613.0651  ]]

 [[ 871.3932    592.7049  ]]

 [[ 638.2186    574.1437  ]]

 [[ 393.91605   553.048   ]]

 [[ 142.07297   531.7721  ]]

 [[1094.9742    431.02078 ]]

 [[ 886.2447    410.12195 ]]

 [[ 670.7023    388.06015 ]]

 [[ 446.

In [23]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

In [1]:
import pickle
pickfle = open("camera_matrix.pckl","rb")
mtx,dist = pickle.load(pickfle)

In [29]:
import pickle
x = open("camera_matrix.pckl","wb")
pickle.dump([mtx,dist],x)
x.close()